name: multi_window_manager
description: Flutter desktop plugin for creating and managing multiple windows, including resizing, repositioning, and inter-window communication.
version: 1.1.1
homepage: https://github.com/vvlad-islavs/multi-window-manager
repository: https://github.com/vvlad-islavs/multi-window-manager
issue_tracker: https://github.com/vvlad-islavs/multi-window-manager/issues
platforms:
  #linux:
  macos:
  windows:
topics:
  - window
  - window-resize
  - window-manager
  - multi-window
  - desktop

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0
  path: ^1.8.0
  screen_retriever: ^0.2.0

dev_dependencies:
  dependency_validator: ^4.1.1
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.2

flutter:
  plugin:
    platforms:
      #linux:
      #  pluginClass: MultiWindowManagerPlugin
      macos:
        pluginClass: MultiWindowManagerPlugin
      windows:
        pluginClass: MultiWindowManagerPlugin
